<?xml version="1.0"?>

<root xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="box_urdf" params="LENGTH WIDTH HEIGHT">  

    <link name="base_footprint"/>

    <link name="base_link">
      <inertial>
        <mass value="100" />
        <origin xyz="0 0 0" />
        <inertia 
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0" 
          izz="1.0" />
      </inertial>
    </link>
    
    <joint name="base_footprint_to_base_link" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${HEIGHT/2.0}" rpy="0 0 0"/>
    </joint>
    
    <link name="body">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LENGTH} ${WIDTH} ${HEIGHT}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0.0</mu>
              <mu2>0.0</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LENGTH} ${WIDTH} ${HEIGHT}"/>
        </geometry>
        <material name="white"/>
      </visual>
    </link>
    
    <joint name="base_link_to_body" type="fixed">
      <parent link="base_link"/>
      <child link="body"/>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

</root>